### ISSUE TITLE
Images and link preview

### ISSUE THREAD

**Issue by oliveirarafa** [fischervincent/semantic-release-discord#2]
I'm using the package and it works very well. Thank you.

I was wondering if it is possible to send images with the message and/or preview the links that I include.

Also I noticed that the link for the Discord API (https://api.discord.com/docs/message-formatting) is offline. Don't know the right one, but that one is offline.

Thanks!

**Comment by fischervincent** [comment]
Thank you, I updated the readme with a fresh [link](https://discord.com/developers/docs/resources/webhook#execute-webhook).
About images/preview I'm not sure, you can check the new link to the discord doc and maybe play with [https://discohook.org/](https://discohook.org/)

**Comment by oliveirarafa** [comment]
Well, looking into the discord.js and your code I managed to incluide image and thumbnail. Its the first time that i'm using discord.js but I think I did it correctly.

Anyway, thank you. This package is really helping me. 👍
