### ISSUE TITLE
Thread Name

### ISSUE THREAD

**Issue by oliveirarafa** [fischervincent/semantic-release-discord#3]
I'm trying to use the `thread_name` JSON param on the `onSuccessTemplate` but can't get the API to work.

Is it possible to make like a spread to anything that I include on the `onSuccessTemplate` to be used on the API? Or am I using it wrong?

It's because I need to use a webhook on a forum channel on discord and it is kind of new.

**Comment by fischervincent** [comment]
I would have thought it would work. I didn't not try on a forum channel.
Do you have an error message that might help me investigate? Also if you can send the template you are trying to use it might help me find the issue.

**Comment by oliveirarafa** [comment]
Yeah, for what I searched the code I tought it would work too. Probably i'm doing something wrong since I dont have a lot of pratice with discord APIs.

My plugin config is:

```javascript
...
[
      "semantic-release-discord",
      {
        notifyOnFail: false,
        onSuccessTemplate: {
          thread_name: "GOVBR-DS ($package_name) v$npm_package_version",
          content:
            "A versão v$npm_package_version do GOVBR-DS ($package_name) já está disponível no NPMJS! :partying_face:\n\nPara conhecer melhor as novidades:\n\n:book: [Página de releases]($repo_url/-/releases 'Releases')\n\n:computer: [Repositório no Gitlab]($repo_url)\n\nDeseja contribuir com o Design System? Consulte a nossa [wiki](https://govbr-ds.gitlab.io/govbr-ds-wiki/ 'Wiki GOVBR-DS') para mais detalhes.",
          embeds: [
            {
              color: 16736031,
              description: "$release_notes",
              title: "RELEASE NOTES",
              url: "$repo_url/-/releases/$npm_package_version",
            },
          ],
          username: "GOVBR-DS - Core v$npm_package_version",
        },
      },
    ]
```

I get the following error message:

```text
[1:41:28 AM] [semantic-release] › ✔  Completed step "fail" of plugin "semantic-release-discord"
[1:41:28 AM] [semantic-release] › ✖  DISCORD CALL FAILED Webhooks posted to forum channels must have a thread_name or thread_id
AggregateError: 
    SemanticReleaseError: Webhooks posted to forum channels must have a thread_name or thread_id
        at module.exports (/builds/govbr-ds/dev/govbr-ds-dev-core/node_modules/semantic-release-discord/src/utils/post-message-to-discord.js:13:11)
```

The messagem tells me that i'm not passing the thread_name to the API call, but I tried putting the param on different places with different strings and got the same result. Using the same webhook and the CLI I managed to post a message on the forum to see that it works. The command that I used on CLI was:

```bash
curl https://discord.com/api/webhooks/[ID]/[TOKEN] -H "Content-Type: application/json" --data '{"thread_name": "Thread Name", "content": "Content", "username": "Blue"}'
```

**Comment by fischervincent** [comment]
My guess is that it is "discord.js" the issue (v12). I will try to use the last version of discord.js, if nothing breaks I will push it.
I will let you know.

**Comment by fischervincent** [comment]
I upgraded discordjs to 14.
I was not able to create a forum so I could not try the fix.
Let me know if that solves the issue.
[1.2.0](https://www.npmjs.com/package/semantic-release-discord/v/1.2.0)

**Comment by oliveirarafa** [comment]
Ok. I'll try and let you know. Thank you very much!

**Comment by oliveirarafa** [comment]
> Ok. I'll try and let you know. Thank you very much!

Well, now it is working.

It needed 2 things:

1. Update discord.js
2. Use threadName instead of thread_name

The second really bugged me but I found a documentation [here](https://discordjs.guide/additional-info/changes-in-v14.html#webhook-1) with the correct name.

Now its is working. Thank you very much!
